// SPDX-License-Identifier: GNU AGPLv3
pragma solidity 0.8.19;

error ERC20InsufficientAllowance(uint256 currentAllowance);
error InsufficientFunds();
error ZeroAddress();
error ERC20PermitExpired();
error ERC20PermitInvalidSignature(address recoveredAddress);
error InsufficientShares(uint256 balanceOfOwner);
error InactiveStrategy(address strategy);
error InactiveVault();
error StrategyIsShutdown();
error ExceedDepositLimit(uint256 recipientMaxDeposit);
error ZeroValue();
error StrategyDebtIsLessThanAssetsNeeded(uint256 strageyCurrentDebt);
error MaxLoss();
error InsufficientAssets(uint256 currTotalIdle, uint256 requestedAssets);
error TooMuchLoss();
error InvalidAssetDecimals();
error UsingModule();
error AlreadyInitialized();
error AmountTooHigh();
error ERC20ApprovalFailed();
error ERC20TransferFailed();
error InvalidAsset(address asset);
error StrategyAlreadyActive();
error StrategyHasDebt(uint256 debt);
error DebtDidntChange();
error StrategyHasUnrealisedLosses(uint256 unrealisedLosses);
error DebtHigherThanMaxDebt(uint256 newDebt, uint256 maxDebt);
error UsingDepositLimit();
error ProfitUnlockTimeTooLong();
